languageCode = "en-us"
title = "crypto.amsterdam"
baseURL = "http://crypto.amsterdam/"

[[menu.main]]
name = "Home"
weight = 1
identifier = "home"
url = "/"

[[menu.main]]
name = "Blog"
weigth = 2
identifier = "blog"
url = "/blog"

[[menu.main]]
name = "Calendar"
weigth = 2
identifier = "calendar"
url = "/calendar"
